export {default as Home} from './Home'
export {default as UsuariosPrestamistas} from './UsuariosPrestamistas'
export {default as UsuariosClientes} from './UsuariosClientes'
export {default as OperacionPrestamos} from './OperacionPrestamos'
export {default as NotFound} from './NotFound'