export {default as Footer} from './Footer'
export {default as Header} from './Header'
export {default as Nav} from './Nav'
export {default as Administrador} from './Administrador'
export {default as AltaPrestamista} from './AltaPrestamista'
export {default as AltaCliente} from './AltaCliente'